In [1]:
import camelot
import pandas as pd
from pathlib import Path

def pdf_read():
    pfile = input(r"Enter PDF Address")
    table1 = camelot.read_pdf(pfile,pages='1,2,3,4,5,6',shift_text=['r','t'])
    return table1

def time_date_scrapper(tables,sec,sub_sec):
    sectd={'Monday':{},'Tuesday':{},'Wednesday':{},'Thursday':{},'Friday':{}}

    for j in range(6):
        page=j
        for index, rows in tables[page].df.iterrows():
            for i,j in enumerate(rows):
                
                if sec in j:           
                    sectd[tables[page].df.iloc[1,0]][f"Time :{tables[page].df.iloc[2,i]}"]=tables[page].df.iloc[index,i].replace("\n"," ")
                if sub_sec in j:             
                    sectd[tables[page].df.iloc[1,0]][f"Time :{tables[page].df.iloc[2,i]}"]=tables[page].df.iloc[index,i].replace("\n"," ")
    return sectd            
def data_frame_wrangler(datascrap):
    data1=pd.DataFrame(datascrap)
    data2=data1.sort_index()
    data2=data2.fillna("No Class")
    return data2


tab=pdf_read()
isec1=input("Enter The Section(in caps)")
isec=f"[{isec1}]"
isubsec=input("Enter The Subsection(If Any)")
scrapped_dict=time_date_scrapper(tab,isec,isubsec)
final_dataframe=data_frame_wrangler(scrapped_dict)
final_dataframe

Enter PDF AddressC:\Users\Hassam Jawed\projects\project timetable\Timetable.pdf
Enter The Section(in caps)2B
Enter The Subsection(If Any)2B1

,Monday,Tuesday,Wednesday,Thursday,Friday
Time :08:30 - 09:20,No Class,No Class,Communication skills TBA [2B],No Class,Communication skills TBA [2B]
Time :09:30 - 10:20,No Class,No Class,Communication skills TBA [2B],OOP Ms. Shafaq [2B],No Class
Time :10:30 - 11:20,Probability Ms. Tehniat [2B],No Class,No Class,No Class,Probability Ms. Tehniat [2B]
Time :11:30 - 12:20,Probability Ms. Tehniat [2B],OOP Ms. Shafaq [2B],No Class,No Class,No Class
Time :12:30 - 13:20,DLD Ms. Samia [2B],No Class,No Class,DLD Lab CS2B1,No Class
Time :13:30 - 14:20,No Class,No Class,OOP Ms. Shafaq [2B],No Class,No Class
Time :14:00 - 14:50,No Class,No Class,No Class,No Class,DLD Ms. Samia [2B]
Time :14:30 - 15:20,No Class,No Class,No Class,DLD Ms. Samia [2B],No Class
Time :15:30 - 16:20,OOP Lab CS2B1 (Ms. Maleeha),No Class,No Class,No Class,No Class

NameError: name 'final_dataframe' is not defined